import { KeyboardControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Experience from "~/components/Experience";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      {/* <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        <div className={"fixed left-0 top-0 h-screen w-screen bg-slate-200"}>
          <KeyboardControls
            map={[
              { name: "forward", keys: ["ArrowUp", "KeyW"] },
              { name: "backward", keys: ["ArrowDown", "KeyS"] },
              { name: "leftward", keys: ["ArrowLeft", "KeyA"] },
              { name: "rightward", keys: ["ArrowRight", "KeyD"] },
              { name: "jump", keys: ["Space"] },
            ]}
          >
            <Canvas
              shadows
              camera={{
                fov: 45,
                near: 0.1,
                far: 200,
                position: [2.5, 4, 6],
              }}
            >
              <ambientLight intensity={0.3} />
              <Experience />
            </Canvas>
          </KeyboardControls>
        </div>
      </main>
    </>
  );
};

export default Home;
